### PR TITLE
Add @yatingupta10 to the repo

### PR DESCRIPTION
**Pull request by yatingupta10**
Adds @yatingupta10 to the personal-sites repo.

Links added:
http://www.yatingupta.me/
https://github.com/yatingupta10

### CODE REVIEW

**Comment by yatingupta10** [comment]
@iangcarroll kindly accept the PR

**Comment by iangcarroll** [comment]
Hi, please delete the `readme.md~` and `github.md` files from your pull request.

**Comment by yatingupta10** [comment]
@iangcarroll  Thanks! my links are already there(another pull request).

**Comment by yatingupta10** [comment]
I am closing this request

**Pull request closed without merging**
