### PR TITLE
Separate out the personal websites and the GitHub profiles

### PR DESCRIPTION
**Pull request by cassidoo**
Addressing #212.  Separates out the GitHub profiles and websites into their own files.

### CODE REVIEW

**Comment by iangcarroll** [comment]
LGTM

**Comment by bryangarza** [comment]
💪 thanks @cassidoo

**Comment by bryangarza** [comment]
Is the github link broken?

**Comment by iangcarroll** [comment]
I spoke too soon - it looks like your markdown formatting is reversed. It's linking to `click here` instead of `github.md`.

**Comment by bryangarza** [comment]
Fixed in https://github.com/HackathonHackers/personal-sites/commit/a41378a8e0307b559cb76e85d8ded27a23b4ac4a.

**Pull request merged**
