### PR TITLE
added Gary-Yau Chan http://garyyauchan.com

### PR DESCRIPTION
**Pull request by chany2**
Adds @chany2 to the personal-sites repo.

Links added:
- http://garyyauchan.com
- https://github.com/chany2

Notes:
www.TheProductHackers.com

### CODE REVIEW

**Comment by cassidoo** [comment]
You only added your personal site, wanna add your GitHub, too?

**Comment by chany2** [comment]
thanks, added Gary-Yau Chan https://github.com/chany2

**Comment by iangcarroll** [comment]
Looks like your GitHub isn't in ABC order.

**Comment by chany2** [comment]
thanks

**Pull request merged**
